@app_url=http://localhost:5063
@dapr_http_url=http://localhost:3501


### Pay via Dapr endpoint
POST {{dapr_http_url}}/v1.0/invoke/payment/method/pay
Content-Type: application/json

{
    "requestId": "{{$guid}}",
    "name": "Marc",
    "totalCost": 100
}


### Pay via app endpoint
POST {{app_url}}/pay
Content-Type: application/json

{
    "requestId": "{{$guid}}",
    "name": "Marc",
    "totalCost": 100
}


### Refund via app endpoint
POST {{app_url}}/refund
Content-Type: application/json

{
    "requestId": "{{$guid}}",
    "name": "Marc",
    "totalCost": 100
}