@dapr_url=http://localhost:3500 
@workflow_id={{$guid}}

###
### Run Hello World workflow
###
// @name wfrequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/HelloWorldWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/text/plain

"World"


### Get status for Hello World workflow
@workflow_helloworld_id_response={{wfrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_helloworld_id_response}}

###
### Run Chaining workflow
### 
// @name wfchainingrequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/ChainingWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/text/plain

"World"

### Get status for Chaining workflow
@workflow_chaining_id_response={{wfchainingrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_chaining_id_response}}

###
### Run FanOutFanIn workflow
### 
// @name wfchainingrequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/FanOutFanInWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/json

[
    "Amsterdam",
    "Chicago",
    "New York"
]

### Get status for FanOutFanIn workflow
@workflow_chaining_id_response={{wfchainingrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_chaining_id_response}}

###
### Run Monitor workflow
### 
// @name wfcontinuerequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/MonitorWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/text/plain

0

### Get status for Monitor workflow
@workflow_continue_id_response={{wfcontinuerequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_continue_id_response}}

###
### Run Timer workflow (use UTC time)
### 
// @name wftimerrequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/TimerWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/json

{
    "DateTime": "2023-09-25T13:20:00+00:00",
    "Name": "World"
}

### Get status for Timer workflow
@workflow_timer_id_response={{wftimerrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_timer_id_response}}

###
### Run External interaction workflow
### 
// @name externalrequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/ExternalInteractionWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/text/plain

"World"

###
### Raise an event
### 
@workflow_external_id_response={{externalrequest.response.body.instanceID}}
@event_name=approval-event
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_external_id_response}}/raiseEvent/{{event_name}}
Content-Type: application/json

{
    "IsApproved" : true
}

### Get status for External interaction workflow
GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_external_id_response}}