@app_url=http://localhost:5064

### Get inventory
GET {{app_url}}/inventory

### Restock inventory
POST {{app_url}}/inventory/restock

### Clear inventory
DELETE {{app_url}}/inventory

### Run workflow
@dapr_url=http://localhost:3500 
@workflow_id={{$guid}}

// @name wfrequest
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/CheckoutWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/json

{
    "Name": "Paperclips",
    "Quantity": 25
}

### Get status
@workflow_id_response={{wfrequest.response.body.instanceID}}

GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/{{workflow_id_response}}