### Restock
@app_url=http://localhost:5064

GET {{app_url}}/stock/restock

### Run workflow
@dapr_url=http://localhost:3500 
POST {{dapr_url}}/v1.0-alpha1/workflows/dapr/OrderProcessingWorkflow/1234/start
Content-Type: application/json

{
    "input" : {"Name": "Paperclips", "TotalCost": 99.95, "Quantity": 1}
}

### Get status

GET {{dapr_url}}/v1.0-alpha1/workflows/dapr/OrderProcessingWorkflow/1234